/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import ButtonPinkImage from 'src/assets/images/writeinvitation_button_pink.png';
import LetterImage from 'src/assets/images/writeinvitation_letter.png';
import EnvelopeImage from 'src/assets/images/writeinvitation_envelope.png';
import { styled } from '@mui/material/styles';

const WriteInvitation1 = styled('div')({
  backgroundColor: `rgba(255, 184, 188, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `844px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Group5 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `240px`,
  height: `54.55px`,
  left: `74px`,
  top: `726px`,
});

const ButtonPink = styled('img')({
  height: `54.55px`,
  width: `240px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `DNF Bit Bit TTF`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  WebkitTextStroke: `1.2000000476837158px rgba(75, 44, 46, 1)`,
  position: `absolute`,
  left: `26px`,
  top: `14px`,
});

const Letter = styled('img')({
  height: `532.5px`,
  width: `300px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `45px`,
  top: `77px`,
});

const Q1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `159px`,
  height: `121px`,
  position: `absolute`,
  left: `114px`,
  top: `116px`,
});

const Q2 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(188, 137, 141, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `128px`,
  top: `98px`,
});

const Rectangle10 = styled('div')({
  backgroundColor: `rgba(245, 222, 216, 1)`,
  borderRadius: `40px`,
  width: `218px`,
  height: `322px`,
  position: `absolute`,
  left: `84px`,
  top: `248px`,
});

const Q3 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(224, 190, 181, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `128px`,
  top: `304px`,
});

const Envelope = styled('img')({
  height: `166.67px`,
  width: `150px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `224px`,
  top: `511px`,
});

function WriteInvitation(props) {
  return (
    <WriteInvitation1 className={props.className}>
      <Group5>
        <ButtonPink src={ButtonPinkImage} loading="lazy" alt={'button_pink'} />
        <Q>{`초대장 링크 복사하기`}</Q>
      </Group5>
      <Letter src={LetterImage} loading="lazy" alt={'letter'} />
      <Q1>
        {`______ 의 파티에
초대합니다!`}
      </Q1>
      <Q2>{`닉네임`}</Q2>
      <Rectangle10></Rectangle10>
      <Q3>{`초대 메세지 작성`}</Q3>
      <Envelope src={EnvelopeImage} loading="lazy" alt={'envelope'} />
    </WriteInvitation1>
  );
}

export default WriteInvitation;
