/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import CakeImage from 'src/assets/images/home_cake.png';
import ButtonLoginImage from 'src/assets/images/home_button_login.png';
import { styled } from '@mui/material/styles';

const Home1 = styled('div')({
  backgroundColor: `rgba(255, 184, 188, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `844px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Cake = styled('img')({
  height: `350px`,
  width: `350px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `20px`,
  top: `267px`,
});

const Title = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `DNF Bit Bit TTF`,
  fontWeight: `400`,
  fontSize: `45px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  textShadow: `7px 8px 4px rgba(0, 0, 0, 0.25)`,
  WebkitTextStroke: `2px rgba(21, 50, 28, 1)`,
  position: `absolute`,
  left: `35px`,
  top: `101px`,
});

const ButtonLogin = styled('img')({
  height: `54.55px`,
  width: `240px`,
  position: `absolute`,
  left: `75px`,
  top: `679px`,
});

function Home(props) {
  return (
    <Home1 className={props.className}>
      <Cake src={CakeImage} loading="lazy" alt={'cake'} />
      <Title>{`This Is For You`}</Title>
      <ButtonLogin src={ButtonLoginImage} loading="lazy" alt={'button_login'} />
    </Home1>
  );
}

export default Home;
