/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Rectangle9Image from 'src/assets/images/avatar_Rectangle_9.png';
import ArrowLeftImage from 'src/assets/images/avatar_arrow_left.png';
import Rectangle8Image from 'src/assets/images/avatar_Rectangle_8.png';
import ArrowRightImage from 'src/assets/images/avatar_arrow_right.png';
import Rectangle81Image from 'src/assets/images/avatar_Rectangle_8_1.png';
import ArrowLeftBodyImage from 'src/assets/images/avatar_arrow_left_body.png';
import ArrowRightHatImage from 'src/assets/images/avatar_arrow_right_hat.png';
import ArrowLeftClotheImage from 'src/assets/images/avatar_arrow_left_clothe.png';
import ArrowRightClotheImage from 'src/assets/images/avatar_arrow_right_clothe.png';
import ArrowLeftHatImage from 'src/assets/images/avatar_arrow_left_hat.png';
import ArrowRightHat1Image from 'src/assets/images/avatar_arrow_right_hat_1.png';
import Body1Image from 'src/assets/images/avatar_________body_1.png';
import HeadImage from 'src/assets/images/avatar_________head.png';
import Q8Image from 'src/assets/images/avatar_______.png';
import GreenHoodImage from 'src/assets/images/avatar_green_hood.png';
import Q9Image from 'src/assets/images/avatar______.png';
import { styled } from '@mui/material/styles';

const Avatar2 = styled('div')({
  backgroundColor: `rgba(255, 184, 188, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `844px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Rectangle9 = styled('img')({
  height: `250px`,
  width: `250px`,
  position: `absolute`,
  left: `70px`,
  top: `29px`,
});

const Q = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `350px`,
  height: `71px`,
  left: `20px`,
  top: `320px`,
});

const ArrowLeft = styled('img')({
  height: `69.82px`,
  width: `64px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `1px`,
});

const Rectangle8 = styled('img')({
  height: `71px`,
  width: `191px`,
  position: `absolute`,
  left: `80px`,
  top: `0px`,
});

const ArrowRight = styled('img')({
  height: `69.82px`,
  width: `64px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `286px`,
  top: `1px`,
});

const Q1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `DNF Bit Bit TTF`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  WebkitTextStroke: `1.2000000476837158px rgba(21, 50, 28, 1)`,
  position: `absolute`,
  left: `134px`,
  top: `23px`,
});

const Q2 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `350px`,
  height: `71px`,
  left: `20px`,
  top: `436px`,
});

const Rectangle81 = styled('img')({
  height: `71px`,
  width: `191px`,
  position: `absolute`,
  left: `80px`,
  top: `0px`,
});

const ArrowLeftBody = styled('img')({
  height: `69.82px`,
  width: `64px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `1px`,
});

const ArrowRightHat = styled('img')({
  height: `69.82px`,
  width: `64px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `286px`,
  top: `1px`,
});

const Q3 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `DNF Bit Bit TTF`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  WebkitTextStroke: `1.2000000476837158px rgba(75, 44, 46, 1)`,
  position: `absolute`,
  left: `143px`,
  top: `23px`,
});

const Q4 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `350px`,
  height: `71px`,
  left: `20px`,
  top: `552px`,
});

const ArrowLeftClothe = styled('img')({
  height: `69.82px`,
  width: `64px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `1px`,
});

const ArrowRightClothe = styled('img')({
  height: `69.82px`,
  width: `64px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `286px`,
  top: `0px`,
});

const Rectangle82 = styled('div')({
  backgroundColor: `rgba(255, 233, 234, 1)`,
  borderRadius: `40px`,
  width: `191px`,
  height: `71px`,
  position: `absolute`,
  left: `80px`,
  top: `0px`,
});

const Q5 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `DNF Bit Bit TTF`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  WebkitTextStroke: `1.2000000476837158px rgba(21, 50, 28, 1)`,
  position: `absolute`,
  left: `143px`,
  top: `23px`,
});

const Q6 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `350px`,
  height: `71.82px`,
  left: `20px`,
  top: `668px`,
});

const Rectangle83 = styled('div')({
  backgroundColor: `rgba(255, 233, 234, 1)`,
  borderRadius: `40px`,
  width: `191px`,
  height: `71px`,
  position: `absolute`,
  left: `80px`,
  top: `0px`,
});

const Q7 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `DNF Bit Bit TTF`,
  fontWeight: `400`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  WebkitTextStroke: `1.2000000476837158px rgba(75, 44, 46, 1)`,
  position: `absolute`,
  left: `133px`,
  top: `23px`,
});

const ArrowLeftHat = styled('img')({
  height: `69.82px`,
  width: `64px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `2px`,
});

const ArrowRightHat1 = styled('img')({
  height: `69.82px`,
  width: `64px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `286px`,
  top: `2px`,
});

const Group4 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `200px`,
  height: `200px`,
  left: `95px`,
  top: `64px`,
});

const Body1 = styled('img')({
  height: `200px`,
  width: `200px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Head = styled('img')({
  height: `200px`,
  width: `200px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q8 = styled('img')({
  height: `200px`,
  width: `200px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const GreenHood = styled('img')({
  height: `200px`,
  width: `200px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Q9 = styled('img')({
  height: `54.55px`,
  width: `120.01px`,
  position: `absolute`,
  left: `250px`,
  top: `773px`,
});

function Avatar1(props) {
  return (
    <Avatar2 className={props.className}>
      <Rectangle9 src={Rectangle9Image} loading="lazy" alt={'Rectangle 9'} />
      <Q>
        <ArrowLeft src={ArrowLeftImage} loading="lazy" alt={'arrow_left'} />
        <Rectangle8 src={Rectangle8Image} loading="lazy" alt={'Rectangle 8'} />
        <ArrowRight src={ArrowRightImage} loading="lazy" alt={'arrow_right'} />
        <Q1>{`머리 선택`}</Q1>
      </Q>
      <Q2>
        <Rectangle81
          src={Rectangle81Image}
          loading="lazy"
          alt={'Rectangle 8'}
        />
        <ArrowLeftBody
          src={ArrowLeftBodyImage}
          loading="lazy"
          alt={'arrow_left_body'}
        />
        <ArrowRightHat
          src={ArrowRightHatImage}
          loading="lazy"
          alt={'arrow_right_hat'}
        />
        <Q3>{`몸 선택`}</Q3>
      </Q2>
      <Q4>
        <ArrowLeftClothe
          src={ArrowLeftClotheImage}
          loading="lazy"
          alt={'arrow_left_clothe'}
        />
        <ArrowRightClothe
          src={ArrowRightClotheImage}
          loading="lazy"
          alt={'arrow_right_clothe'}
        />
        <Rectangle82></Rectangle82>
        <Q5>{`옷 선택`}</Q5>
      </Q4>
      <Q6>
        <Rectangle83></Rectangle83>
        <Q7>{`모자 선택`}</Q7>
        <ArrowLeftHat
          src={ArrowLeftHatImage}
          loading="lazy"
          alt={'arrow_left_hat'}
        />
        <ArrowRightHat1
          src={ArrowRightHat1Image}
          loading="lazy"
          alt={'arrow_right_hat'}
        />
      </Q6>
      <Group4>
        <Body1 src={Body1Image} loading="lazy" alt={'고양이body 1'} />
        <Head src={HeadImage} loading="lazy" alt={'고양이head'} />
        <Q8 src={Q8Image} loading="lazy" alt={'새싹'} />
        <GreenHood src={GreenHoodImage} loading="lazy" alt={'green_hood'} />
      </Group4>
      <Q9 src={Q9Image} loading="lazy" alt={'다음단계'} />
    </Avatar2>
  );
}

export default Avatar1;
