/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import QImage from 'src/assets/images/login_______.png';
import Q1Image from 'src/assets/images/login________.png';
import Q2Image from 'src/assets/images/login_______________.png';
import Q3Image from 'src/assets/images/login_________.png';
import LoginCImage from 'src/assets/images/login_loginC.png';
import Q4Image from 'src/assets/images/login_________1.png';
import Q5Image from 'src/assets/images/login________________1.png';
import Q6Image from 'src/assets/images/login________1.png';
import { styled } from '@mui/material/styles';

const Login1 = styled('div')({
  backgroundColor: `rgba(255, 184, 188, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `844px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const Q = styled('img')({
  height: `54.55px`,
  width: `240px`,
  position: `absolute`,
  left: `75px`,
  top: `481px`,
});

const Q1 = styled('img')({
  height: `54.55px`,
  width: `240px`,
  position: `absolute`,
  left: `66px`,
  top: `709px`,
});

const Q2 = styled('img')({
  height: `51px`,
  width: `154px`,
  position: `absolute`,
  left: `117px`,
  top: `636px`,
});

const Q3 = styled('img')({
  height: `51px`,
  width: `92px`,
  position: `absolute`,
  left: `92px`,
  top: `201px`,
});

const LoginC = styled('img')({
  height: `122.37px`,
  width: `217px`,
  position: `absolute`,
  left: `84px`,
  top: `59px`,
});

const Q4 = styled('img')({
  height: `77px`,
  width: `290px`,
  position: `absolute`,
  left: `49px`,
  top: `349px`,
});

const Q5 = styled('img')({
  height: `55px`,
  width: `171px`,
  position: `absolute`,
  left: `110px`,
  top: `380px`,
});

const Q6 = styled('img')({
  height: `79px`,
  width: `291px`,
  position: `absolute`,
  left: `49px`,
  top: `239px`,
});

const Q7 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  color: `rgba(188, 137, 141, 1)`,
  fontStyle: `normal`,
  fontFamily: `PFStardust`,
  fontWeight: `500`,
  fontSize: `17px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `175px`,
  position: `absolute`,
  left: `108px`,
  top: `272px`,
});

function Login(props) {
  return (
    <Login1 className={props.className}>
      <Q src={QImage} loading="lazy" alt={'로그인버튼'} />
      <Q1 src={Q1Image} loading="lazy" alt={'회원가입버튼'} />
      <Q2 src={Q2Image} loading="lazy" alt={'아직 회원이 아니신가요?'} />
      <Q3 src={Q3Image} loading="lazy" alt={'회원이신가요?'} />
      <LoginC src={LoginCImage} loading="lazy" alt={'loginC'} />
      <Q4 src={Q4Image} loading="lazy" alt={'비밀번호입력'} />
      <Q5 src={Q5Image} loading="lazy" alt={'비밀번호를 입력해주세요!'} />
      <Q6 src={Q6Image} loading="lazy" alt={'아이디입력'} />
      <Q7>{`메일 주소를 입력해주세요!`}</Q7>
    </Login1>
  );
}

export default Login;
